# Generated by Django 3.2.8 on 2023-07-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(verbose_name='cid')),
                ('classs', models.CharField(max_length=20, verbose_name='classs')),
                ('img', models.ImageField(upload_to='img', verbose_name='imgurl')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('descriptionall', models.CharField(max_length=600, verbose_name='descriptionall')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('img', models.ImageField(upload_to='img', verbose_name='imgurl')),
            ],
        ),
        migrations.CreateModel(
            name='UandC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('cid', models.IntegerField(verbose_name='cid')),
                ('RC', models.IntegerField(verbose_name='RC')),
                ('times', models.DateTimeField(null=True, verbose_name='time')),
            ],
        ),
    ]
