# Generated by Django 3.2.8 on 2023-07-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(verbose_name='cid')),
                ('classs', models.CharField(max_length=20, verbose_name='classs')),
                ('images', models.CharField(max_length=100, verbose_name='images')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('images', models.CharField(max_length=100, verbose_name='images')),
            ],
        ),
        migrations.CreateModel(
            name='UandC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('cid', models.IntegerField(verbose_name='cid')),
                ('times', models.IntegerField(verbose_name='times')),
            ],
        ),
    ]
