# Generated by Django 3.2.8 on 2023-07-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='static/img', verbose_name='imgurl'),
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(upload_to='static/img', verbose_name='imgurl'),
        ),
    ]
