# Generated by Django 3.2.8 on 2023-08-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uandp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(verbose_name='cid')),
                ('keshi', models.IntegerField(verbose_name='keshi')),
                ('show1', models.ImageField(upload_to='static/img', verbose_name='show1')),
                ('show2', models.ImageField(upload_to='static/img', verbose_name='show2')),
                ('show3', models.ImageField(upload_to='static/img', verbose_name='show3')),
                ('show4', models.ImageField(upload_to='static/img', verbose_name='show4')),
            ],
        ),
    ]
