# Generated by Django 3.2.8 on 2023-08-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_candimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDI',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField(verbose_name='cid')),
                ('times', models.DateTimeField(null=True, verbose_name='times')),
            ],
        ),
        migrations.CreateModel(
            name='DLI',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('IP', models.CharField(max_length=300, verbose_name='IP')),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('times', models.DateTimeField(null=True, verbose_name='times')),
            ],
        ),
        migrations.CreateModel(
            name='QDI',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('cid', models.IntegerField(verbose_name='cid')),
                ('times', models.DateTimeField(null=True, verbose_name='times')),
            ],
        ),
    ]
