# Generated by Django 3.2.8 on 2023-08-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bdi_dli_qdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdi',
            name='uid',
            field=models.IntegerField(default=1, verbose_name='uid'),
            preserve_default=False,
        ),
    ]
