# Generated by Django 3.2.8 on 2023-08-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bdi_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='plun',
            fields=[
                ('plid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(max_length=1024, verbose_name='content')),
                ('times', models.DateTimeField(null=True, verbose_name='times')),
            ],
        ),
        migrations.CreateModel(
            name='UCI',
            fields=[
                ('ucid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('times', models.DateTimeField(null=True, verbose_name='times')),
            ],
        ),
    ]
